package com.aletheion.cartomancy

import org.json.JSONArray
import org.json.JSONObject

object ArtifactRenderer {
    fun toJson(reading: ReadingArtifact): String {
        val root = JSONObject()
            .put("type", "tarot-reading")
            .put("schema_version", "1.0")
            .put("architecture", reading.architecture)
            .put("draw_status", reading.drawStatus)
            .put("date", reading.date)
            .put("deck", reading.deck)
            .put("spread", reading.spread)
            .put("mode", reading.mode)
            .put("symbolic_corpus", reading.deck)
            .put("receptive_formation", reading.spread)
            .put("interpretation_protocol", reading.mode)
            .put("epistemic_framework", "default-symbolic-inquiry")
            .put("audit_layer", "standard-outcome-audit")
            .put("question", reading.question)
            .put("context", reading.context)
            .putNullable("confidence", reading.confidence)
            .put("first_impression", reading.firstImpression)
            .put("cards", JSONArray(reading.cards.map(::cardJson)))
            .put("tags", JSONArray(reading.tags))
            .put("review_status", reading.reviewStatus)
            .putNullable("review_date", reading.reviewDate)
            .putNullable("usefulness_score", reading.usefulnessScore)
            .putNullable("projection_risk", reading.projectionRisk)
            .putNullable("action_taken", reading.actionTaken)
            .put("claim_types", JSONArray(reading.claimTypes))
        return root.toString(2) + "\n"
    }

    fun toMarkdown(reading: ReadingArtifact): String = buildString {
        appendLine("---")
        appendLine("type: tarot-reading")
        appendLine("schema_version: \"1.0\"")
        appendLine("architecture: ${reading.architecture}")
        appendLine("draw_status: ${reading.drawStatus}")
        appendLine("date: ${reading.date}")
        appendLine("deck: ${reading.deck}")
        appendLine("spread: ${reading.spread}")
        appendLine("mode: ${reading.mode}")
        appendLine("symbolic_corpus: ${reading.deck}")
        appendLine("receptive_formation: ${reading.spread}")
        appendLine("interpretation_protocol: ${reading.mode}")
        appendLine("epistemic_framework: default-symbolic-inquiry")
        appendLine("audit_layer: standard-outcome-audit")
        appendLine("question: ${yamlString(reading.question)}")
        appendLine("context: ${yamlString(reading.context)}")
        appendLine("confidence: ${reading.confidence ?: ""}")
        appendLine("first_impression: ${yamlString(reading.firstImpression)}")
        appendLine("cards:")
        reading.cards.forEach { card ->
            appendLine("  - position: ${card.position}")
            appendLine("    card: ${yamlString(card.card.name)}")
            appendLine("    orientation: ${card.orientation}")
        }
        appendLine("tags:")
        reading.tags.forEach { appendLine("  - ${yamlString(it)}") }
        appendLine("review_status: ${reading.reviewStatus}")
        appendLine("review_date: ${reading.reviewDate ?: ""}")
        appendLine("usefulness_score: ${reading.usefulnessScore ?: ""}")
        appendLine("projection_risk: ${reading.projectionRisk ?: ""}")
        appendLine("action_taken: ${yamlString(reading.actionTaken ?: "")}")
        appendLine("claim_types:")
        reading.claimTypes.forEach { appendLine("  - ${yamlString(it)}") }
        appendLine("---")
        appendLine()
        appendLine("# Kybernion Reading - ${reading.date}")
        appendLine()
        appendLine("## Question")
        appendLine()
        appendLine(reading.question)
        appendLine()
        appendLine("## Context")
        appendLine()
        appendLine(reading.context)
        appendLine()
        appendLine("## Confidence")
        appendLine()
        appendLine(reading.confidence?.toString() ?: "")
        appendLine()
        appendLine("## Spread")
        appendLine()
        appendLine(reading.spread)
        appendLine()
        appendLine("## Cards Drawn")
        appendLine()
        appendLine("| Position | Card | Orientation | Keywords |")
        appendLine("| --- | --- | --- | --- |")
        reading.cards.forEach { card ->
            appendLine("| ${card.position}. ${card.positionLabel} | ${card.card.name} | ${card.orientation} | ${card.keywords.joinToString(", ")} |")
        }
        appendLine()
        appendLine("## Epistemic Claim Types")
        appendLine()
        appendLine("Use these labels while interpreting:")
        appendLine()
        appendLine("- Observation:")
        appendLine("- Symbolic association:")
        appendLine("- Intuition:")
        appendLine("- Interpretation:")
        appendLine("- Prediction:")
        appendLine("- Action recommendation:")
        appendLine()
        appendLine("## First Impression")
        appendLine()
        appendLine(reading.firstImpression)
        appendLine()
        appendLine("## Guidebook / Reference Notes")
        appendLine()
        appendLine("## Later Interpretation")
        appendLine()
        appendLine("## Action Chosen")
        appendLine()
        appendLine("## 72-Hour Experiment")
        appendLine()
        appendLine("## Follow-Up")
        appendLine()
        appendLine("## Outcome / Audit")
        appendLine()
        appendLine("### Review Metadata")
        appendLine()
        appendLine("- Review date:")
        appendLine("- Time elapsed:")
        appendLine("- Reading mode: ${reading.mode}")
        appendLine("- Original confidence: ${reading.confidence ?: ""}")
        appendLine()
        appendLine("### What Actually Happened?")
        appendLine()
        appendLine("### What Action Did I Take?")
        appendLine()
        appendLine("### What Did I Avoid?")
        appendLine()
        appendLine("### Which Parts Were Useful?")
        appendLine()
        appendLine("### Which Parts Were Projection?")
        appendLine()
        appendLine("### Did This Clarify Action?")
        appendLine()
        appendLine("- Yes / No / Mixed")
        appendLine()
        appendLine("### Usefulness Score")
        appendLine()
        appendLine("- Score: /5")
        appendLine()
        appendLine("### Projection Risk")
        appendLine()
        appendLine("- Low / Medium / High")
        appendLine()
        appendLine("### Notes for Future Readings")
    }

    private fun cardJson(card: DrawnCard): JSONObject = JSONObject()
        .put("position", card.position)
        .put("position_label", card.positionLabel)
        .put("position_prompt", card.positionPrompt)
        .put("card_id", card.card.id)
        .put("card", card.card.name)
        .put("arcana", card.card.arcana)
        .put("number", card.card.number)
        .putNullable("suit", card.card.suit)
        .putNullable("element", card.card.element)
        .put("orientation", card.orientation)
        .put("keywords", JSONArray(card.keywords))

    private fun yamlString(value: String): String {
        val escaped = value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\r", "\\r")
            .replace("\n", "\\n")
        return "\"$escaped\""
    }
}

private fun JSONObject.putNullable(name: String, value: Any?): JSONObject = put(name, value ?: JSONObject.NULL)
